### ISSUE TITLE
Broken icon on Windows 10 22H2

### ISSUE THREAD

**Issue by B1ue-Dev** [Pinguin2001/Bluebird-Browser#1]
The image below is pretty much self-explained. Is it a font issue on my side or the project using SegoeUI icons that only available on Windows 11?

![image](https://user-images.githubusercontent.com/60958064/231866999-ba8a3c8c-e2a7-4693-8bbd-1f7e042229b6.png)

**Comment by Pinguin2001** [comment]
Hello there, you are right. This is indeed an issue, I will migrate to MDL2 as long as Windows 10 is supported, once it will be out-of-support I will migrate to Segoe Fluent Icons (or whatever icon font Windows vNext will use)

**Comment by Pinguin2001** [comment]
![image](https://user-images.githubusercontent.com/75797743/232123081-2d0f99c8-2acc-4aea-ab2b-9e2df659b219.png)
Good news, I have found a workaround. On Windows 10 MDL2 and on Windows 11 Segoe Fluent Icons will be used

**Comment by B1ue-Dev** [comment]
Have you uploaded the fix to MS Store yet?

**Comment by Pinguin2001** [comment]
Not yet, I will in the coming days
